// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

function createSupabaseClient() {
  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

function missingConfigResult() {
  const message =
    'Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in .env or your host settings.';
  return { data: null, error: { message, name: 'ConfigError' } };
}

/** Safe proxy: never throws at import time; returns errors when Supabase env is missing. */
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!isSupabaseConfigured) {
      if (prop === 'auth') {
        return new Proxy(
          {},
          {
            get() {
              return () => Promise.resolve(missingConfigResult());
            },
          },
        );
      }
      if (prop === 'from') {
        return () =>
          new Proxy(
            {},
            {
              get() {
                return () => Promise.resolve(missingConfigResult());
              },
            },
          );
      }
      if (prop === 'channel') {
        return () => ({
          on: () => ({ subscribe: () => ({}) }),
        });
      }
      if (prop === 'removeChannel') {
        return () => {};
      }
      if (prop === 'rpc') {
        return () => Promise.resolve(missingConfigResult());
      }
      return undefined;
    }
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
